name: Fetch and Update Google Sheet

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows for manual trigger

jobs:
  update-google-sheets:  # This must be indented under `jobs`
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify a compatible Python version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google Cloud credentials
        run: echo "$TS_CREDENTIALS" > credentials.json
        env:
          TS_CREDENTIALS: ${{ secrets.TS_CREDENTIALS }}

      - name: Run Python script
        run: python tesouro_transparente.py

        - name: Debug TS_CREDENTIALS
        run: echo "$TS_CREDENTIALS" | jq '.'
        env:
          TS_CREDENTIALS: ${{ secrets.TS_CREDENTIALS }}

