name: Fetch and Update Google Sheet

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows for manual trigger

jobs:
  update-google-sheets:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2  # Fetch the repository contents

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use a recent Python version

      # Step 3: Install dependencies
     - name: Install dependencies
    run: |
    pip install --upgrade pip
    pip install --force-reinstall - requirements.txt

      # Step 4: Set up Google Cloud credentials
      - name: Set up Google Cloud credentials
        run: echo "$TS_CREDENTIALS" > credentials.json
        env:
          TS_CREDENTIALS: ${{ secrets.TS_CREDENTIALS }}  # Use the secret you added in GitHub

      # Step 5: Run your Python script
      - name: Run Python script
        run: python tesouro_transparente.py  # Replace 'tesouro_transparente.py' with the name of your Python script
